config/routes.rb
KicksAreSick::Application.routes.draw do
  post   'customers',       to: 'customer#create'
  get "orders/new",         to: 'orders#new',                     as: 'orders_new'
  get  'homepage',          to: 'homepage#index',                 as: 'index'
  get  'contact_us',        to: 'contact#index',                  as: 'contact_us'
  get  'about_us',          to: 'about#index',                    as: 'about_us'
  get  'product',           to: 'products#index',                 as: 'products'
  get  'categories',        to: 'category#index',                 as: 'categories'
  get  'shoes',             to: 'products#shoes_category',        as: 'shoes'
  get  'accessories',       to: 'products#acc_category',          as: 'accessories'
  get  'equipments',        to: 'products#equip_category',        as: 'equipments'
  get  'search_results',    to: 'products#search_results',        as: 'search_results'
  post 'product/:id',       to: 'orders#add_to_cart',             as: 'add_to_cart'
  get  'cart',              to: 'orders#cart_items',              as: 'cart'
  get  'order/:id',         to: 'orders#show',                    as: 'order_review'
  get  'customer/new',      to: 'customer#new',                   as: 'new_customer'
  get  'order_complete',    to: 'orders#index',                   as: 'order_complete'
  root :to => "homepage#index"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :products
  resources :category, only: [:index, :show ]
  resources :customer, only: [:new, :create]
  

end

app/models/about.rb
class About < ActiveRecord::Base
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  has_many  :products
  validates :name, presence: true
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
  validates :name, presence: true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :orders
  belongs_to :province
  validates :fname, :lname, :phone, :address, :city, :postal_code, presence: true
end

app/models/hompage.rb
class Hompage < ActiveRecord::Base
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :order
  
  validates :price, :quantity, numericality: {greater_than_or_equal_to: 0}
  validates :price, :quantity, presence: true
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many   :line_items
  has_many   :products, :through => :line_items
  belongs_to :customer
  
  validates :status, presence: true
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to        :category
  belongs_to        :brand
  belongs_to        :sale_status
  validates         :name, :price, :category_id, :quantity, presence: true
  
  attr_accessor :default_url, :default_style
  
  has_attached_file :image,
                    :styles => { :large => "500x500>", :medium => "300x300!", :thumb => "100x100>" },
                    :default_url => "/images/:style/missing.png" 
                   
  
              
  validates_attachment_size :image, :less_than => 5.megabytes
  validates_attachment_content_type :image, :content_type => ['image/jpeg', 'image/png']
  
  def remove_photo=(value)
     self.image.destroy if value == '1'
  end
  
  def remove_photo
  		'0'
  end
  
  def self.keyword_search(keywords,category)
      keywords = "%" + keywords + "%"
    if category == "" then
      Product.where("name LIKE ? OR description LIKE ?", keywords, keywords)
    else
      Product.where("name LIKE ? AND category_id = ?  OR description LIKE ? AND category_id = ?", keywords,category,keywords,category)
      
    end    
    
  end
      
end

app/models/province.rb
class Province < ActiveRecord::Base
  has_many :customer
  validates :name, presence: true
  validates :pst, :gst, numericality: {less_than_or_equal_to: 0.8, greater_than_or_equal_to: 0}
end

app/models/sale_status.rb
class SaleStatus < ActiveRecord::Base
  has_many :products
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/brand_helper.rb
module BrandHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/shared/_headnav.html.erb
<div id="head_nav">
	<ul id="navlist">
		<li><%= link_to 'Home',  root_path %></li>
		<li><%= link_to 'Products',  products_path %></li>
		<li><%= link_to 'Category',  categories_path %></li>
		<li><%= link_to 'Brand',  'admin/contacts/1/edit' %></li>
		<li><%= link_to 'Contact Us',  contact_us_path %></li>
		<li class="rightnav"><%= link_to 'About Us',  about_us_path %></li>
	</ul>
</div>

<hr>

app/views/shared/_products.html.erb
<section>
<h3>Products</h3>
<div id="products">
	
	<% @products.each do |product| %>

	<p>
		<strong><%= link_to product.name, product%></strong>
		</p>
    <% if product.image.present? %>
      <p>
        <%= image_tag product.image.url(:thumb) %>
      </p>
    <% end %>
		<p><%= product.description %></p>
  
    <p><strong>Brand:</strong> <%= product.brand.name %></p>
    <p>
		<strong>Stocks Remaining: </strong>
		<%= number_to_human product.quantity %>
		</p>
    <p><strong>Price:</strong> <%= number_to_currency product.price%></p>
	<% if product.onsale_price.present? %>
	<p id="sale_price"><strong>Sale Price:</strong> <%= number_to_currency product.onsale_price%></p>
	<% end %>
<hr>


<% end %>
<div id="paginate">
<%= paginate @products %>
</div>
</div>	
</section>

app/views/shared/_searchbar.html.erb
<section id="searchncart">

	<div id="searchbar">
<%= form_tag search_results_path, method: 'get' do %>
<%= image_tag("logo.jpg") %>
 	<span class="bar"><%= text_field_tag(:search_keywords) %></span>
 <%= select_tag (:category_option), options_from_collection_for_select(Category.all, :id, :name), prompt: "All Categories" %>
 <%= submit_tag "Search"%>
<% end %>
</div>
	
<div id="cartstat">
		<ul id="cartnav">
	   	<li class="items"><%= link_to pluralize(@item_count, "item"), cart_path %></li>
	    <li><%= link_to "Check out", new_customer_path %></li>
		</ul>
</div>	
</section>