config/routes.rb
KicksAreSick::Application.routes.draw do
  post   'customers',       to: 'customer#create'
  get "orders/new",         to: 'orders#new',                     as: 'orders_new'
  get  'homepage',          to: 'homepage#index',                 as: 'index'
  get  'contact_us',        to: 'contact#index',                  as: 'contact_us'
  get  'about_us',          to: 'about#index',                    as: 'about_us'
  get  'product',           to: 'products#index',                 as: 'products'
  get  'categories',        to: 'category#index',                 as: 'categories'
  get  'shoes',             to: 'products#shoes_category',        as: 'shoes'
  get  'accessories',       to: 'products#acc_category',          as: 'accessories'
  get  'equipments',        to: 'products#equip_category',        as: 'equipments'
  get  'search_results',    to: 'products#search_results',        as: 'search_results'
  post 'product/:id',       to: 'orders#add_to_cart',             as: 'add_to_cart'
  get  'cart',              to: 'orders#cart_items',              as: 'cart'
  get  'order/:id',         to: 'orders#show',                    as: 'order_review'
  get  'customer/new',      to: 'customer#new',                   as: 'new_customer'
  get  'order_complete',    to: 'orders#index',                   as: 'order_complete'
  root :to => "homepage#index"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :products
  resources :category, only: [:index, :show ]
  resources :customer, only: [:new, :create]
  

end

app/models/about.rb
class About < ActiveRecord::Base
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  has_many  :products
  validates :name, presence: true
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
  validates :name, presence: true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :orders
  belongs_to :province
  validates :fname, :lname, :phone, :address, :city, :postal_code, presence: true
end

app/models/hompage.rb
class Hompage < ActiveRecord::Base
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :order
  
  validates :price, :quantity, numericality: {greater_than_or_equal_to: 0}
  validates :price, :quantity, presence: true
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many   :line_items
  has_many   :products, :through => :line_items
  belongs_to :customer
  
  validates :status, presence: true
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to        :category
  belongs_to        :brand
  belongs_to        :sale_status
  validates         :name, :price, :category_id, :quantity, presence: true
  
  attr_accessor :default_url, :default_style
  
  has_attached_file :image,
                    :styles => { :large => "500x500>", :medium => "300x300!", :thumb => "100x100>" },
                    :default_url => "/images/:style/missing.png" 
                   
  
              
  validates_attachment_size :image, :less_than => 5.megabytes
  validates_attachment_content_type :image, :content_type => ['image/jpeg', 'image/png']
  
  def remove_photo=(value)
     self.image.destroy if value == '1'
  end
  
  def remove_photo
  		'0'
  end
  
  def self.keyword_search(keywords,category)
      keywords = "%" + keywords + "%"
    if category == "" then
      Product.where("name LIKE ? OR description LIKE ?", keywords, keywords)
    else
      Product.where("name LIKE ? AND category_id = ?  OR description LIKE ? AND category_id = ?", keywords,category,keywords,category)
      
    end    
    
  end
      
end

app/models/province.rb
class Province < ActiveRecord::Base
  has_many :customer
  validates :name, presence: true
  validates :pst, :gst, numericality: {less_than_or_equal_to: 0.8, greater_than_or_equal_to: 0}
end

app/models/sale_status.rb
class SaleStatus < ActiveRecord::Base
  has_many :products
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Kaminari.paginate_array(Product.find(:all, :include => [:category,:brand], :order => "name ASC")).page(params[:page]).per(3)
    @categories = Category.order(:name)
  end
  
  def shoes_category
     @products = Kaminari.paginate_array(Product.where('category_id = 1')).page(params[:page]).per(3)
    
  end
  
  def acc_category
     @products = Kaminari.paginate_array(Product.where('category_id = 2')).page(params[:page]).per(3)
  end
  
  def equip_category
     @products = Kaminari.paginate_array(Product.where('category_id = 3')).page(params[:page]).per(3)
  end
  
  def search_results
     @products = Kaminari.paginate_array(Product.keyword_search(params[:search_keywords],params[:category_option])).page(params[:page]).per(3)
    
    if @products.length == 0 && params[:category_option] == "" 
         flash[:results] = "No available products found which match your selection for: \"#{params[:search_keywords]}\" "
         
    elsif @products.length == 0 && params[:category_option] != 
         flash[:results] = "No available products found which match your selection for: \"#{params[:search_keywords]}\" in this category " 
    else
         flash[:results] = "Search results:"
    end
  
         
    
  end
  

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :image, :category_id, :description, :brand_id, :quantity, :price, :destroy)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/brand_helper.rb
module BrandHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/provinces_helper.rb
module ProvincesHelper
end

app/views/products/_form.html.erb
<%= form_for(@product, :html => {:multipart => true}) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.number_field :category_id %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :brand_id %><br>
    <%= f.number_field :brand_id %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image%>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/equip_category.html.erb
<%= render 'shared/products' %>

app/views/products/index.html.erb
<%= render 'shared/products' %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/search_results.html.erb
<% flash.each do |flash| %>
  <h3><%= flash[1] %></h3>
<% end %>
<%= render :partial => "shared/products", :object => @products %>

app/views/products/shoes_category.html.erb
<%= render 'shared/products' %>

app/views/products/show.html.erb
<section id="view_prod">
<p>
  <%= image_tag @product.image.url(:thumb) %>
</p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @product.brand_id %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @product.quantity %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

 <% if session[:items].include?(@product.id) then %>
      <h4>This item is currently in your cart.</h4>
    <% else %>      
      <%= form_tag add_to_cart_path %>
      <div>
			  <%= label_tag 'qty', 'Quantity:' %>
			  <%= text_field_tag 'qty', value="1" %>
        <%= button_tag 'Add to Cart', data: {@product.id => :id, @qty => :qty}, class: "btn 		btn-default btn-sm" %>
      </div>      
    <%end%>    
		
<section>